config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
 get '/mypost/:user_id', to:'posts#mypost'
  devise_for :users
  root 'posts#index'
post "mycomments/:comment_id" =>"comments#mycomment" ,as: "mycomment"
 
  resources :posts do
    resources :comments
  end
  resources :comments do
   resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :commentable, polymorphic: true
    has_many :comments,as: :commentable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
has_many :comments, as: :commentable
  has_many :taggings,dependent: :destroy
  has_many :tags, through: :taggings
  validates :body, presence: true 
  def all_tags=(names)
    self.tags=names.split(",").map do |name|
      Tag.where(name: name).first_or_create!
    end
  end
   
  def all_tags
    tags.map(&:name).join(",")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:is_female,:dob])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @post=Post.find(params[:post_id])
    @comment=@post.comments.create(comment_params)

    if @comment.save
      flash[:success]='Comment Posted'
      respond_to do |format|
        format.html { redirect_to post_path(@post)}
        format.js #render comments/create.js.erb
    end
  end

end
def mycomment
 @comment=Comment.find(params[:comment_id])
 @com=@comment.comments.create(comm_params)

 redirect_to posts_path
end

private
def comment_params
  params[:comment][:user_id] = current_user.id

 params.require(:comment).permit(:body, :comment_id, :user_id)
end
def comm_params
  params[:comment][:commentable_type]="Comment"
  params[:comment][:user_id] = current_user.id

  params.require(:comment).permit(:body, :comment_id , :commentable_type, :user_id)
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
    @post=Post.order('updated_at DESC')  
    end
    def new
    @post=Post.new
    end
    def edit
     @post = Post.find(params[:id])
    end
    def create
    @post=Post.new(post_params)
    if @post.save
      redirect_to  posts_index_path
      flash[:success] = 'Your Article has been sent to Admin for publishing!'

    else
      render 'new'
      flash[:warning] = 'Something went wrong.'

    end
    end
    def show
    @post=Post.all

    end
    def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to posts_path
   end
   def edit
    @post = Post.find(params[:id])
    
   end
   def update
     @post = Post.find(params[:id])
     
 
  if @post.update(post_update_params)

    redirect_to posts_path
    flash[:success] = 'Update Sucessfull!'

  else
    render 'edit'
    flash[:warning] = 'Something went wrong.'

  end
end
def show
    @post = Post.find(params[:id])
  end
  
  def mypost
    @post=User.find(params[:user_id]).posts
  end
     

     private
        def post_params
        params[:post][:user_id] = current_user.id
         params.require(:post).permit(:title,:body,:user_id,:all_tags,:published)
      end
      def post_update_params
        params[:post][:user_id] = @post.user_id
         params.require(:post).permit(:title,:body,:user_id,:all_tags,:published)
      end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<script>
function myFunction() {
  var x = document.getElementById("myDIV");
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>
<p>
  
<%=comment.body %>
&nbsp;&nbsp;&nbsp;<strong> Commenter :<%=User.where(:id=>comment.user_id).first.try(:name) %></strong>





  <% comment.comments.each do |f|%>
    &nbsp;&nbsp;&nbsp;&nbsp;<%=f.body%>
    &nbsp;&nbsp;&nbsp;&nbsp; :<%=time_ago_in_words(comment.created_at)%> &nbsp; ago
 <br>
<%end%>




<br>
<%= form_for "comment",url: mycomment_path(comment) do |f| %>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.text_field :body %>
  

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= f.submit "Reply"%>
  
<% end %>


</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build],remote:true) do |f|%>  
    <p>
    <%=f.text_area :body %>
    
    </p>
    
    
    <p>
    <%= f.submit%>
      </p>
    
    
    
    <%end%>

app/views/comments/create.js.erb
$('#com_content').append("<%= j  render @comment%>");
$(':text').val("");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogProj</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
  <div class="navbar-header">
  <a class="navbar-brand" href="#">BloggersPoint.com</a>
</div>
    <ul class="nav navbar-nav navbar-right">
<li> <button class="btn btn-danger"><%= link_to('logout',destroy_user_session_path,:method => :delete)%></button></li>
<li><button class="btn btn-sucess"><%= link_to('New Posts',new_post_path)%></button></li>
</ul>
</div>
</nav>
<h1 align="center" style="color:#221349;"  font-family: 'Lato', sans-serif;><big><big>Edit article</big></big></h1>
<article id="tbg"align="center">

<%= form_for @post  do  |form|%>
  <p>
<%= form.label :title %><br>
<%= form.text_field :title ,:style =>"width:50%;height:50px;"%>
</p>
 
<p>
<%= form.label :body %><br>
<%= form.text_area :body,:style =>"width:100%;height:500px;" %>
</p>
<% if user_signed_in? && current_user.utype=='admin'%>

<p>
Status<br>
Publish<%= form.radio_button :published,"true"%> 
&nbsp;&nbsp; Unpublish<%= form.radio_button :published,"false"%> 
</P>
<%end%>
  <p>
    <%= form.submit %>
  </p>
<% end %>

</article>

app/views/posts/index.html.erb
<% if !user_signed_in? %>

<nav class="navbar navbar-inverse">

  <div class="container-fluid">
  <div class="navbar-header">
      <a class="navbar-brand" href="#">BloggersPoint.com</a>
    </div>
    
<ul class="nav navbar-nav navbar-right">
<li><a href="/users/sign_in" class="btn btn-info" style="float:right;margin-top:15px;margin-left:10px;"><font color="white">Login</font></a></li>
<li><a href="/users/sign_up" class="btn btn-info" style="float:right;margin-top:15px;margin-left:10px;"><font color="white">SignUp</font></a></li>
</ul>

</div>

</nav>
<div class="alert alert-info" align="center">
  <strong><big><big>Hey!!Not a member, Click SignUp at top right  Corner</big></big></strong>
</div><div id="tbg" class="table-responsive"> 
<table  cellpadding="10px" align="center" class="table table-hover">
<thead bgcolor="#CAC9C9">
<tr>
<td><strong><big>Title</strong></big></td>
<td><strong><big>Name</strong></big></td>
<td><strong><big>Created By</strong></big></td>
<td><strong><big>Created at</strong></big></td>
<td><strong><big>Last Comment</strong></big></td>
<td><strong><big>Last Commenter</strong></big></td>
<td><strong><big>Status</strong></big></td>

</tr>
</thead>
<% @post.each do |f| %>
  <%if f.published==true%>

<div id="tbg">
    <tr>
<td><%= f.title %></td>
<td><%= f.user.name %></td>
<td><%= f.user.email %></td>
<td><%= time_ago_in_words(f.updated_at)%> ago</td>
<td><%= f.comments.last.try(:body) %></td>
<td><%=User.where(:id => f.comments.last.try(:user_id)).first&.name %></td>

<td>Published</td>


</div>
</tr>
<%end%>
<% end %>

</table>

</div>

<%end%>
<% if user_signed_in? && current_user.utype=='admin'%>
<nav class="navbar navbar-inverse">

  <div class="container-fluid">
  <div class="navbar-header">
      <a class="navbar-brand" href="#">BloggersPoint.com</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
<li><button class="btn btn-danger" ><%= link_to('logout',destroy_user_session_path,:method => :delete )%></button></li>
<li><button class="btn btn-info"><%= link_to('New Posts',new_post_path)%></button></li>
<li><button class="btn btn-warning"><a href="/mypost/<%= current_user.id %>">My Posts</a></button></li>
</ul>
</div>
</nav>
<h1 align="center" style="color:#221349;"  font-family: 'Lato', sans-serif;>WELCOME ADMIN  <%= current_user.name %></h1>
<big><strong>Signed in as..  <%= current_user.email %></strong></big>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="table-responsive"> 
<table id="tbg" cellpadding="10px" align="center" class="table table-hover">
<thead bgcolor="#CAC9C9">

<tr>
<td><strong><big>Title</big></strong></td>

<td><strong><big>Name</strong></big></td>

<td><strong><big>Created at</strong></big></td>

<td><strong><big>Email</strong></big></td>
<td><strong><big>Status</strong></big></td>

<td><strong><big>Delete Articles</strong></big></td>

<td><strong><big>Edit Articles</strong></big></td>
<td><strong><big>Show Articles</strong></big></td>
</tr>
</thead>
<% @post.each do |f| %>
  <div id="tbg">
<tr>
<td><%= f.title %></td>
<td><%= f.user.name %></td>
<td><%= f.created_at %></td>
<td><%= f.user.email %></td>
<%if f.published==false ||f.published==nil  %>
<td>Unpublished</td>

<% else %>
<td>Published</td>
<%end%>
<td><button type="button" class="btn btn-danger"><%= link_to 'Destroy', post_path(f),
              method: :delete,
              data: { confirm: 'Are you sure?'},class: 'link_color' %></button></td>
 <td> <button type="button" class="btn btn-warning"><%= link_to 'Edit', edit_post_path(f) ,class: 'link_color'%></button>
</td>
 <td><button type="button" class="btn btn-info"><%= link_to 'Show', post_path(f),class: 'link_color' %></button></td>

</tr>
</div>
<% end %>

</table>

</div>
<%end%>
 

<% if user_signed_in?  && current_user.utype==nil%>


<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">BloggersPoint.com</a>
    </div>
   
    <ul class="nav navbar-nav navbar-right">

    
    <button type="button" class="btn btn-warning"><li><%= link_to('New Posts',new_post_path)%></li></button>
    <li><button type="button" class="btn btn-info"><a href="/mypost/<%= current_user.id %>">My Posts</a></button></li>
    <button type="button" class="btn btn-danger"> <li><%= link_to('logout',destroy_user_session_path,:method => :delete)%></li></button>

</ul>
</div>

</nav>

<big><strong>Signed in as... <%= current_user.email %><big><strong>
<h1 align="center" style="color:#221349;"  font-family: 'Lato', sans-serif;>WELCOME  <%= current_user.name %></h1>

<div class="table-responsive"> 
<table id="tbg" cellpadding="10px" align="center" class="table table-hover">
<thead bgcolor="#CAC9C9">
<tr>
<td><strong><big>Title</strong></big></td>
<td><strong><big>Name</strong></big></td>
<td><strong><big>Email id</strong></big></td>
<td><strong><big>Created at</strong></big></td>
<td><strong><big>Show</strong></big></td>
</tr>
</thead>
<% @post.each do |f| %>
  <%if f.published==true%>

<tr>
<td><%= f.title %></td>
<td><%= f.user.name %></td>
<td><%= f.user.email %></td>
<td><%= f.created_at %></td>
<td><button type="button" class="btn btn-info"><%= link_to 'Show', post_path(f),class: 'link_color' %></button></td>

</tr>
<% end %>
<%end%>
</table>
</div>

<%end%>

app/views/posts/mypost.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
  <div class="navbar-header">
  <a class="navbar-brand" href="#">BloggersPoint.com</a>
</div>
    <ul class="nav navbar-nav navbar-right">
<li> <button class="btn btn-danger"><%= link_to('logout',destroy_user_session_path,:method => :delete)%></button></li>
<li><button class="btn btn-sucess"><%= link_to('New Posts',new_post_path)%></button></li>
</ul>
</div>
</nav>
<h1 align="center" style="color:#221349;"  font-family: 'Lato', sans-serif;><big><big>Your Post</big></big></h1>
<div class="table-responsive"> 
<table id="tbg" cellpadding="10px" align="center" class="table table-hover">
<thead bgcolor="#CAC9C9">
<tr>
<td><strong><big>Title</strong></big></td>
<td><strong><big>Created at</strong></big></td>
<td><strong><big>Name</strong></big></td>
<td><strong><big>Destroy Article</strong></big></td>
<td><strong><big>Edit Article</strong></big></td>
<td><strong><big>Show Article</strong></big></td>
<td><strong><big>Status</strong></big></td>

</tr>

</thead>
<% @post.each do |f| %>

<tr>
<td><%= f.title %></td>
<td><%= f.created_at %></td>
<td><%= f.user.name %></td>
<td><button class="btn btn-danger"><%= link_to 'Destroy', post_path(f),
              method: :delete,
              data: { confirm: 'Are you sure?' } ,class: 'link_color' %></button></td>
 <td> <button class="btn btn-warning"><%= link_to 'Edit', edit_post_path(f) %></button>
</td>
 <td><button class="btn btn-info"><%= link_to 'Show', post_path(f) %></td></button>
<%if f.published==nil || f.published==false%>
<td>Unpublished</td>
<%else%>
<td>Published</td>
<%end%>
</tr>

<% end %>
</table>
</div>

app/views/posts/new.html.erb
<article id="tbg"align="center">
<%= form_for @post  do  |form|%>
  <p>
<%= form.label :title %><br>
<%= form.text_field :title ,:style =>"width:50%;height:50px;"%>
</p>
 
<p>
<%= form.label :body %><br>
<%= form.text_area :body ,:style =>"width:90%;height:500px;"%>
</p>
<p>
<%= form.label :all_tags %><br>
<%= form.text_area :all_tags ,:style =>"width:50%;height:50px;" %> (seperated by comma(,) )
</p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</article>

app/views/posts/show.html.erb
<h1  align="center" >
 <big> <%= @post.title %></big>
  
  </h1>
  <hr>
  
  <article id="tbg" align="left">    

  
<%=simple_format @post.body %>
</p>


</article>

<div align="center">
<strong>Tags:</strong>
<% @post.all_tags.split(",").each do |post|%>
  <button class="btn btn-default"><%= post %> </button> 
 <%end%>
 </div>
<div id="comment">

<strong>Add a comment:</strong>
<div id="com_content">
<%= render @post.comments%>
</div>
</div>
<%= render 'comments/form' %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>